backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

# editorial workflow allows posts to have an "in review" status
publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images

# Collections contain the different types of content we will create and publish
collections:
  - name: "blog"
    label: "Blog"
    folder: "website/src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # We will use the hidden templateKey field to map files to their corresponding template
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "events"
    label: "Events"
    folder: "website/src/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # We will use the hidden templateKey field to map files to their corresponding template
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "event-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
